# Generated by Django 4.1.2 on 2022-10-21 08:27

from django.db import migrations, models
import recipes_exam_november_2020.recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_create_recipe_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250, validators=[recipes_exam_november_2020.recipes.validators.ingredients_validator]),
        ),
    ]
